spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Qo93yelf3uqn

server:
  port: 9084

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${server.port}